### ISSUE TITLE
Icons issue

### ISSUE THREAD

**Issue by Muzummil** [wildfirechat/admin#2]
We are using the admin portal of wildfirechat and did some changes but after deploying the code on HTTPS production el icons are not working on production on local those are working fine. Icons are added as CSS pseudo content. Below is the screenshot showing issue. We tried multiple solutions to fix it but are not sure what exactly is the thing causing the issue.
![Screen Shot 2022-07-27 at 5 36 20 PM](https://user-images.githubusercontent.com/48760089/181260565-fdca0fd8-3eca-4a70-a221-d338832c5a36.png)

**Comment by imndx** [comment]
请看看这个[issue](https://github.com/ElemeFE/element/issues/6462)，看看有没有帮助。如果还是不行的话，请微信联系: wfchat

**Comment by Muzummil** [comment]
@imndx I already did that but it didn't work with that. The issue is fixed now by changing the assetsPublicPath value of webpack build file of production due to which it was not been able to take the font file.
Thanks.
